#data source confige

spring:  datasource:    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: kanhu
    
    
  jpa:    properties:      hibernate:
       show_sql: true
       format_sql: true
    hibernate:      ddl-auto: update
server:  port: 6564